"""empty message

Revision ID: 559ec7d236fc
Revises: 
Create Date: 2023-10-18 09:07:17.480766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '559ec7d236fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('_password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users_table')),
    sa.UniqueConstraint('username', name=op.f('uq_users_table_username'))
    )
    op.create_table('friendship_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requestor_id', sa.Integer(), nullable=True),
    sa.Column('requested_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['requested_id'], ['users_table.id'], name=op.f('fk_friendship_table_requested_id_users_table')),
    sa.ForeignKeyConstraint(['requestor_id'], ['users_table.id'], name=op.f('fk_friendship_table_requestor_id_users_table')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_friendship_table'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friendship_table')
    op.drop_table('users_table')
    # ### end Alembic commands ###
